# Generated by nixai devenv
# https://devenv.sh/
{
  # https://devenv.sh/packages/
  packages = [
    git
    curl
    python3Packages.black
    python3Packages.flake8
    python3Packages.pytest
    python3Packages.mypy
  ];
  # https://devenv.sh/languages/
  languages = {
    python = {
      enable = true;
      version = "311";
    };
  };
  # https://devenv.sh/scripts/
  scripts = {
    format = {
      exec = "black .";
    };
    install = {
      exec = "pip install -r requirements.txt";
    };
    lint = {
      exec = "flake8 .";
    };
    run = {
      exec = "python";
    };
    test = {
      exec = "pytest";
    };
    typecheck = {
      exec = "mypy .";
    };
  };
  # https://devenv.sh/environment-variables/
  env = {
    PYTHONPATH = ".";
  };
}
